### ISSUE TITLE
Tmux integration

### ISSUE THREAD

**Issue by LukasDoesDev** [glacambre/nwin#23]
https://github.com/marromlam/sailor.vim allows seamless navigation between Kitty windows, tmux panes and (neo)vim buffers. Could you do something similar or add integration?

**Comment by LukasDoesDev** [comment]
Tmux and nvim in one would be cool. Could you launch Kitty windows/panes or OS windows instead of your custom terminal?

**Comment by glacambre** [comment]
Nwin is not a custom terminal, it's a true neovim GUI. There's nothing to integrate - every neovim window is its own GUI window which you can navigate to and from using your regular window manager keyboard shortcuts.

**Comment by LukasDoesDev** [comment]
Sorry I didn't really think it through. I meant could you support tmux panes along with Neovim buffers and custom terminal emulators/renderers would be nice if possible.?

**Comment by glacambre** [comment]
So you would want a single tmux instance, with one GUI window per tmux pane? This would require re-writing nwin in its entirety, so it's not something I'm interested in (especially since I find tmux redundant - just use Neovim's terminal emulator! :) ).

If this is something you really care about, I imagine that you might be able to implement it yourself by writing a GUI program capable of speaking tmux's protocol. I couldn't find any document detailing this protocol, but you might have better luck either opening an issue in [tmux's repository](https://github.com/tmux/tmux) or asking about it on their [mailing list](mailto:tmux-users@googlegroups.com)

**Comment by LukasDoesDev** [comment]
That's actually smart. Thanks for the idea!
